stages:
  - build
  - test

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git unzip libsqlite3-dev
  - docker-php-ext-install mbstring pdo_sqlite zip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

build:
    stage: build
    tags:
      - qdev
    script:
      - composer install
      - cp .env.testing .env
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan migrate
      - php artisan db:seed

test:
    stage: test
    tags:
      - qdev
    script:
      - php artisan test
